kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-sc-mongo
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-08bf067e9bafb024f
  directoryPerms: "750"
  gidRangeStart: "999" # optional
  gidRangeEnd: "1000" # optional
  basePath: "/dynamic_provisioning_mongo" # optional
  subPathPattern: "${.PVC.namespace}/${.PVC.name}" # optional
  ensureUniqueDirectory: "true" # optional
  reuseAccessPoint: "false" # optional
